allocation/urls.py
from django.urls import path
app_name = "allocation"
from .views import *

urlpatterns = [
    path ("allocate/", allocate, name="allocate"),
]

chief/urls.py
from django.urls import path
app_name = "chief"
from .views import *

urlpatterns = [
    path ("add_chief/", add_chief, name="add_chief"),
]

client/urls.py
from django.urls import path
app_name = "client"
from .views import *

urlpatterns = [
    path ("add/", add_client, name="add_client"),
]

cls/urls.py
from django.contrib import admin
from django.urls import path,include
from staff.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = ( [
    path('admin/', admin.site.urls),
    path('client/', include('client.urls')),
    path('allocation/', include('allocation.urls')),
    path('lands/', include('lands.urls')),
    # path('staff/', include('staff.urls')),
    path('chief/', include('chief.urls')),
    path('', loginIndex),
    path('#',login_sucess, name='login_sucess'),
    # path('accounts/login', loginIndex),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('dashboard', admindashboard, name="admin_dashboard"),
    path('dashboard/chief_records', admin_chief_records, name="admin_chief_records"),
    path('dashboard/chief_records/add_chief', admin_add_chief, name="admin_add_chief"),
   
    path('chief_dashboard/', chief_dashboard, name="chief_dashboard"),
    path('chief_statistics/', chief_statistics, name="chief_statistics"),
    path('chief_dashboard/allocation_chit', allocation_chit, name="chief_allocation_chit"),
    path('chief_dashboard/allocation_chit/edit', edit_allocation_chit, name="edit_allocation_chit"),
    path('chief_dashboard/allocation_chit/add', add_allocation_chit, name="add_allocation_chit"),
    
    path('dashboard/chief_records/edit_chief/<int:id>', admin_edit_chief, name="admin_edit_chief"),
    path('dashboard/chief_records/view_chief/<int:id>', admin_view_chief, name="admin_view_chief"),
    path('dashboard/chief_records/delete_chief/<int:id>', admin_delete_chief, name="admin_delete_chief"),
    path('dashboard/staff_records/add_staff', admin_add_staff, name="admin_add_staff"),
    path('dashboard/staff_records', admin_staff_records, name="admin_staff_records"),
    path('dashboard/staff_records/<str:username>/profile', admin_staff_profile, name="admin_staff_profile"),
    path('dashboard/staff_records/<str:username>/profile/edit', admin_update_staff_profile, name="admin_edit_staffprofile"),
    path('dashboard/staff_records/<str:username>/activate', admin_staff_activate, name="admin_staff_activate"),
    path('dashboard/staff_records/<str:username>/deactivate', admin_staff_deactivate, name="admin_staff_deactivate"),
    path('dashboard/land_records/add_land', admin_add_land, name="admin_add_land"),
    path('dashboard/land_records/edit_land/<int:id>', admin_edit_land, name="admin_edit_land"),
    path('dashboard/land_records', admin_land_records, name="admin_land_records"),
    path('dashboard/client_records', admin_client_records, name="admin_client_records"),
    path('dashboard/client_records/add_client', admin_add_client, name="admin_add_client"),
    path('dashboard/allocation_records', admin_allocation_records, name="admin_allocation_records"),
    path('dashboard/allocation_records/make_allocation', admin_make_allocation, name="admin_make_allocation"),
    path('dashboard/chief_records/edit_allocation/<int:id>', admin_edit_allocation, name="admin_edit_allocation"),
    path('dashboard/chief_records/view_allocation/<int:id>', admin_view_allocation, name="admin_view_allocation"),
    path('dashboard/chief_records/delete_allocation/<int:id>', admin_delete_allocation, name="admin_delete_allocation"),
    path("accounts/", include("django.contrib.auth.urls")),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

templates/add_chief.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
{% block content %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Care Taker Chief Form</h2>
                <form method="POST"action="{% url 'chief:add_chief' %}?next=/"  enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                {{chiefform}}
                                {% comment %} <label class="label">first name</label>
                                <input class="input--style-4" type="text" name="first_name"> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">last name</label>
                                <input class="input--style-4" type="text" name="last_name">
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Birthday</label>
                                <div class="input-group-icon">
                                    <input class="input--style-4 js-datepicker" type="text" name="birthday">
                                    <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Gender</label>
                                <div class="p-t-10">
                                    <label class="radio-container m-r-45">Male
                                        <input type="radio" checked="checked" name="gender">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="radio-container">Female
                                        <input type="radio" name="gender">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Email</label>
                                <input class="input--style-4" type="email" name="email">
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Phone Number</label>
                                <input class="input--style-4" type="text" name="phone">
                            </div>
                        </div>
                    </div>
                    <div class="input-group">
                        <label class="label">Subject</label>
                        <div class="rs-select2 js-select-simple select--no-search">
                            <select name="subject">
                                <option disabled="disabled" selected="selected">Choose option</option>
                                <option>Subject 1</option>
                                <option>Subject 2</option>
                                <option>Subject 3</option>
                            </select>
                            <div class="select-dropdown"></div>
                        </div>
                    </div>
                    <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/add_client.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
{% block content %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Client Registration Form</h2>
                <form method="POST"action="{% url 'client:add_client' %}?next=/"  enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                {{clientform}}
                                {% comment %} <label class="label">first name</label>
                                <input class="input--style-4" type="text" name="first_name"> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">last name</label>
                                <input class="input--style-4" type="text" name="last_name">
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            {% comment %} <div class="input-group">
                                <label class="label">Date of Birth</label>
                                <div class="input-group-icon">
                                    <input class="input--style-4 js-datepicker" type="text" name="birthday">
                                    <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                                </div>
                            </div> {% endcomment %}
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Gender</label>
                                <div class="p-t-10">
                                    <label class="radio-container m-r-45">Male
                                        <input type="radio" checked="checked" name="gender">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="radio-container">Female
                                        <input type="radio" name="gender">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Phone Number</label>
                                <input class="input--style-4" type="text" name="phone">
                            </div>
                        </div>
                    </div>
                    <div class="input-group">
                        <label class="label">Subject</label>
                        <div class="rs-select2 js-select-simple select--no-search">
                            <select name="subject">
                                <option disabled="disabled" selected="selected">Choose option</option>
                                <option>Subject 1</option>
                                <option>Subject 2</option>
                                <option>Subject 3</option>
                            </select>
                            <div class="select-dropdown"></div>
                        </div>
                    </div>
                    <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/add_land.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
{% block content %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Land Registration Form</h2>
                <form method="POST"action="{% url 'land:add_land' %}?next=/"  enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                {{landform}}
                                {% comment %} <label class="label">first name</label>
                                <input class="input--style-4" type="text" name="first_name"> {% endcomment %}
                            </div>
                        </div>
                        
                    </div>
                   
                    <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/add_staff.html
{% extends "base.html" %}

{% block title %}

{% endblock title %}
{% block content %}
{% include 'online/side_nav.html' %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Staff Registration Form</h2>
                <form method="POST"action="{% url 'staff:add_staff' %}?next=/"  enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                {{staffform}}
                                {% comment %} <label class="label">first name</label>
                                <input class="input--style-4" type="text" name="first_name"> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">last name</label>
                                <input class="input--style-4" type="text" name="last_name">
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Birthday</label>
                                <div class="input-group-icon">
                                    <input class="input--style-4 js-datepicker" type="text" name="birthday">
                                    <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Gender</label>
                                <div class="p-t-10">
                                    <label class="radio-container m-r-45">Male
                                        <input type="radio" checked="checked" name="gender">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="radio-container">Female
                                        <input type="radio" name="gender">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Email</label>
                                <input class="input--style-4" type="email" name="email">
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Phone Number</label>
                                <input class="input--style-4" type="text" name="phone">
                            </div>
                        </div>
                    </div>
                  
                    <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>{% block title %} {% endblock title %}</title>

    <!-- Icons font CSS-->
    <link href=" {% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href=" {% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    {% block content %}
    
    {% endblock content %}
    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
{% block content %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Welcome to the Customary Lands System</h2>
                <form method="POST" enctype="multipart/form-data">
                                     
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group  p-t-15">
                                <a href="{% url 'land:add_land'%}" class="btn p-t-15 btn--radius-2 btn--red">Add Land</a>   
                            </div>
                            <div class="input-group p-t-15">
                                <a href="{% url 'chief:add_chief'%}" class="btn btn--radius-2 btn--green">Add CT Chief</a>   
                            </div>

                            <div class="input-group p-t-15">
                                <a href="{% url 'client:add_client'%}" class="btn btn--radius-2 btn--green">Add Client</a>   
                            </div>
                        </div>
                        <div class="col-2 ">
                            {% comment %} <div class="input-group p-t-15">
                                 <a href="{% url 'staff:add_staff'%}" class="p-t-15 btn btn--radius-2 btn--blue">Add CLS Staff</a>    
                            </div> {% endcomment %}
                      
                            <div class="input-group p-t-15">
                                <a href="{% url 'allocation:allocate'%}" class="btn btn--radius-2 btn--green">Allocate</a>
    
                            </div>
                        </div>
                        
                    <!-- <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                    </div> -->
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/make_allocations.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
{% block content %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Allocation Form</h2>
                <form method="POST"action="{% url 'allocation:allocate' %}?next=/"  enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                {{allocationform}}
                                {% comment %} <label class="label">first name</label>
                                <input class="input--style-4" type="text" name="first_name"> {% endcomment %}
                            </div>
                        </div>
                        
                    </div>
                   
                   
                    
                    <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}